### ISSUE TITLE
Questions about the dagger/best_cwnds.yml

### ISSUE THREAD

**Issue by lilyhpeng** [francisyyan/rlcc#2]
Hi:

Sorry to bother you~ I have some questions about how to generate the expert data. I noticed there are some predefined "best_cwnd_map" data in dagger/best_cwnds.yml, but I have no idea how to generate it. 

I'd really appreciate it if you could help me with my questions～

**Comment by francisyyan** [comment]
Hi there -- You could find the way we generated "congestion-control oracles" in our [research paper](https://pantheon.stanford.edu/static/pantheon/documents/pantheon-paper.pdf). Basically for each emulated network path, you need to compute BDP and search around BDP to find out the optimal congestion window size that achieves the best performance (highest throughput and lowest delay). To this end, you can write a simple sender that uses a constant congestion window all the time and test it on the emulated link along with a simple receiver. Then you can vary the congestion window size (e.g., BDP, BDP-10, BDP+10, ...) until the best performance is achieved. Please feel free to let me know if you have any other question in our [Google group](https://groups.google.com/forum/#!forum/pantheon-stanford).
